### ISSUE TITLE
Problem in sync between arduino and the sensel device

### ISSUE THREAD

**Issue by hrishirao** [sensel/sensel-api-arduino#1]
Hi,

I am using the default application of this github library, and I have some issues in having a continuous output on the serial monitor of arduino. It seems like the board prints out x-coordinate, y-coordinate and the force values when I press the board yet but then it prints a bunch of blank lines before printing another line of valid x,y coordinates and the force... sample of the output shown below:

`⸮&Num Contacts: 1
Contact 0: x_pos 167.05 y_pos 72.72 total_force 781.50
⸮&
⸮&
⸮&
⸮&
⸮&Num Contacts: 1
Contact 0: x_pos 166.59 y_pos 72.88 total_force 765.63
⸮&Num Contacts: 1
Contact 0: x_pos 166.56 y_pos 72.90 total_force 764.75
⸮&
⸮&
⸮&
⸮&
⸮&Num Contacts: 1
Contact 0: x_pos 166.41 y_pos 72.92 total_force 700.00
⸮&
⸮&
⸮&
⸮&Num Contacts: 1
Contact 0: x_pos 166.34 y_pos 73.04 total_force 661.88
⸮&Num Contacts: 1
Contact 0: x_pos 166.38 y_pos 73.10 total_force 670.38
⸮&
⸮&
⸮&
⸮&
⸮&Num Contacts: 1
Contact 0: x_pos 166.43 y_pos 73.25 total_force 670.25
⸮&
`

Now I am not sure why I am getting the blank slots in the middle but it makes me think one of the two devices is running slower than the other. Could someone help me debug this issue?

Thanks

**Comment by AlexSensel** [comment]
Hello and thank you for contacting us. To help us debug, what chip or board are you using? We had issues with Software Serial or shared with USB so we recommend a dedicated Hardware Serial. If you are using a hardware serial, we are happy to look into the issue further.

**Comment by hrishirao** [comment]
Hardware serial (replacing arduino uno with a mega basically) did the job! Thank you, your answer helped!
